/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brailleantv2;

import java.awt.Color;

/**
 *
 * @author pi
 */
public class CameraSettingsForm extends javax.swing.JFrame {

    /**
     * Creates new form CameraSettingsForm
     */
    private TTS tts;
    private final CameraSettings config=new CameraSettings(Global.CAMERA_CONFIG_DIR);
    private void init(){
        
        this.getContentPane().setBackground(Color.green);
        slider_Contrast.setValue(Global.map(-100,100,config.contrast,0,100));
        slider_Saturation.setValue(Global.map(-100,100,config.saturation,0,100));
        slider_Brightness.setValue(config.brightness);
        slider_Sharpness.setValue(Global.map(-100,100,config.sharpness,0,100));
        slider_Quality.setValue(config.quality);
        spinner_Width.setValue(config.width);
        spinner_Height.setValue(config.height);
        spinner_ShutterSpeed.setValue(config.shutterSpeed);
        comboBox_Rotation.setSelectedIndex(config.rotation);
        comboBox_Rotation.setEditable(false);
    }
    public CameraSettingsForm() {
        this.tts=new TTS();
        initComponents();
        init();
    }
    public CameraSettingsForm(TTS tts){
        this.tts=tts;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        slider_Contrast = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        slider_Saturation = new javax.swing.JSlider();
        slider_Brightness = new javax.swing.JSlider();
        slider_Quality = new javax.swing.JSlider();
        spinner_Height = new javax.swing.JSpinner();
        spinner_Width = new javax.swing.JSpinner();
        comboBox_Rotation = new javax.swing.JComboBox<>();
        btn_Back = new javax.swing.JButton();
        btn_Apply = new javax.swing.JButton();
        btn_Preview = new javax.swing.JButton();
        btn_Defaults = new javax.swing.JButton();
        spinner_ShutterSpeed = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        slider_Sharpness = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(480, 320));
        setMinimumSize(new java.awt.Dimension(480, 320));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(480, 320));
        setResizable(false);

        jLabel1.setText("Contrast");
        jLabel1.setMaximumSize(new java.awt.Dimension(90, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 25));

        slider_Contrast.setPreferredSize(new java.awt.Dimension(300, 26));
        slider_Contrast.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_ContrastStateChanged(evt);
            }
        });

        jLabel2.setText("Saturation");
        jLabel2.setMaximumSize(new java.awt.Dimension(90, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 25));

        jLabel3.setText("Brightness");
        jLabel3.setMaximumSize(new java.awt.Dimension(90, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 25));

        jLabel4.setText("Rotation");
        jLabel4.setMaximumSize(new java.awt.Dimension(90, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(90, 25));

        jLabel5.setText("Width");
        jLabel5.setMaximumSize(new java.awt.Dimension(90, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 25));

        jLabel6.setText("Height");
        jLabel6.setMaximumSize(new java.awt.Dimension(90, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(90, 25));

        jLabel7.setText("ShutterSpeed");
        jLabel7.setMaximumSize(new java.awt.Dimension(90, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 25));

        jLabel8.setText("Quality");
        jLabel8.setMaximumSize(new java.awt.Dimension(90, 25));
        jLabel8.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel8.setPreferredSize(new java.awt.Dimension(90, 25));

        slider_Saturation.setPreferredSize(new java.awt.Dimension(300, 26));

        slider_Brightness.setPreferredSize(new java.awt.Dimension(300, 26));

        slider_Quality.setPreferredSize(new java.awt.Dimension(300, 26));

        comboBox_Rotation.setEditable(true);
        comboBox_Rotation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "90", "180", "270" }));
        comboBox_Rotation.setSelectedItem(0);
        comboBox_Rotation.setToolTipText("");

        btn_Back.setBackground(java.awt.Color.white);
        btn_Back.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_Back.setText("BACK");
        btn_Back.setMaximumSize(new java.awt.Dimension(115, 60));
        btn_Back.setMinimumSize(new java.awt.Dimension(115, 60));
        btn_Back.setPreferredSize(new java.awt.Dimension(115, 60));
        btn_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BackMouseClicked(evt);
            }
        });

        btn_Apply.setBackground(java.awt.Color.white);
        btn_Apply.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_Apply.setText("APPLY");
        btn_Apply.setMaximumSize(new java.awt.Dimension(115, 60));
        btn_Apply.setMinimumSize(new java.awt.Dimension(115, 60));
        btn_Apply.setPreferredSize(new java.awt.Dimension(115, 60));
        btn_Apply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ApplyMouseClicked(evt);
            }
        });

        btn_Preview.setBackground(java.awt.Color.white);
        btn_Preview.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_Preview.setText("PREVIEW");
        btn_Preview.setMaximumSize(new java.awt.Dimension(115, 60));
        btn_Preview.setMinimumSize(new java.awt.Dimension(115, 60));
        btn_Preview.setPreferredSize(new java.awt.Dimension(115, 60));
        btn_Preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PreviewActionPerformed(evt);
            }
        });

        btn_Defaults.setBackground(java.awt.Color.white);
        btn_Defaults.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_Defaults.setText("DEFAULTS");
        btn_Defaults.setMaximumSize(new java.awt.Dimension(115, 60));
        btn_Defaults.setMinimumSize(new java.awt.Dimension(115, 60));
        btn_Defaults.setPreferredSize(new java.awt.Dimension(115, 60));
        btn_Defaults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DefaultsMouseClicked(evt);
            }
        });

        jLabel9.setText("Sharpness");

        slider_Sharpness.setPreferredSize(new java.awt.Dimension(300, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spinner_ShutterSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slider_Quality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(slider_Contrast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(slider_Saturation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(slider_Sharpness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(slider_Brightness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(spinner_Height, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinner_Width, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBox_Rotation, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Defaults, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Preview, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Apply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider_Contrast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider_Saturation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider_Brightness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(slider_Sharpness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_ShutterSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_Height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_Width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_Rotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider_Quality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Defaults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Preview, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Apply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PreviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PreviewActionPerformed

    private void btn_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BackMouseClicked
        // TODO add your handling code here:
        new CameraForm(this.tts).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackMouseClicked

    private void slider_ContrastStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_ContrastStateChanged
        // TODO add your handling code here:
        System.out.println(slider_Contrast.getValue());
    }//GEN-LAST:event_slider_ContrastStateChanged

    private void btn_ApplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ApplyMouseClicked
        // TODO add your handling code here:
        config.brightness=slider_Brightness.getValue();
        config.saturation=Global.map(0,100,slider_Saturation.getValue(),-100,100);
        config.contrast=Global.map(0,100,slider_Contrast.getValue(),-100,100);
        config.sharpness=Global.map(0,100,slider_Sharpness.getValue(),-100,100);
        config.quality=slider_Quality.getValue();
        config.rotation=comboBox_Rotation.getSelectedIndex();
        config.height=(int)spinner_Height.getValue();
        config.width=(int)spinner_Width.getValue();
        config.shutterSpeed=(int)spinner_ShutterSpeed.getValue();
        config.writeSettings();
    }//GEN-LAST:event_btn_ApplyMouseClicked

    private void btn_DefaultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DefaultsMouseClicked
        // TODO add your handling code here:
        slider_Brightness.setValue(50);
        slider_Saturation.setValue(50);
        slider_Contrast.setValue(50);
        slider_Sharpness.setValue(50);
        slider_Quality.setValue(50);
        comboBox_Rotation.setSelectedIndex(0);
        spinner_Height.setValue(900);
        spinner_Width.setValue(840);
        spinner_ShutterSpeed.setValue(10000);
    }//GEN-LAST:event_btn_DefaultsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CameraSettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CameraSettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CameraSettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CameraSettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CameraSettingsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Apply;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Defaults;
    private javax.swing.JButton btn_Preview;
    private javax.swing.JComboBox<String> comboBox_Rotation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSlider slider_Brightness;
    private javax.swing.JSlider slider_Contrast;
    private javax.swing.JSlider slider_Quality;
    private javax.swing.JSlider slider_Saturation;
    private javax.swing.JSlider slider_Sharpness;
    private javax.swing.JSpinner spinner_Height;
    private javax.swing.JSpinner spinner_ShutterSpeed;
    private javax.swing.JSpinner spinner_Width;
    // End of variables declaration//GEN-END:variables
}
