/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brailleantv2;

/**
 *
 * @author Zildjian
 */
import java.awt.Color;
import java.util.Date;
import java.io.File;
import java.io.FileWriter;
import java.io.BufferedWriter;
public class EditForm extends javax.swing.JFrame {

    /**
     * Creates new form EditForm
     */
    private TTS tts;
    private Spelling spellchecker;
    private String originalString="";
    private String fileName;
    private boolean fromCamera=false;
    private boolean fromRead=false;
    private void init(){
        
        this.getContentPane().setBackground(Color.cyan);
        try{
            spellchecker=new Spelling(Global.DICT_DIR);
            java.io.File file=new java.io.File("/home/pi/Documents/Brailleant/out.txt");
            System.out.println("Filename: "+file.getName());
            Date now=new Date();
            this.txt_filename.setText(now.toString());
            java.util.Scanner sc = new java.util.Scanner(file);
            while (sc.hasNext()) {
                originalString = originalString.concat(sc.nextLine() + "\n");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        this.txt_content.setText(originalString);
        spellchecker.register(txt_content);
    }
    private void init(String filename){
        
        this.getContentPane().setBackground(Color.cyan);
        try{
            System.out.println(Global.DICT_DIR);
            spellchecker=new Spelling(Global.DICT_DIR);
            this.fileName=filename;
            java.io.File file=new java.io.File("/home/pi/Documents/Brailleant/Files/"+filename);
            this.txt_filename.setText(filename);            
            java.util.Scanner sc = new java.util.Scanner(file);
            while (sc.hasNext()) {
                originalString = originalString.concat(sc.nextLine() + "\n");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        this.txt_content.setText(originalString);
        spellchecker.register(txt_content);
    }
    public EditForm() {
        tts=new TTS();
        initComponents();
        init();
    }
    public EditForm(TTS tts) {
        this.tts=tts;
        initComponents();
        init();
        this.fromCamera=true;
    }
    public EditForm(TTS tts,String filename) {
        this.tts=tts;
        initComponents();
        init(filename);
        this.fromRead=true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_content = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txt_filename = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_read = new javax.swing.JButton();
        btn_correct = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(480, 320));
        setMinimumSize(new java.awt.Dimension(480, 320));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(480, 320));
        setResizable(false);

        txt_content.setColumns(20);
        txt_content.setRows(5);
        txt_content.setMaximumSize(null);
        txt_content.setMinimumSize(null);
        txt_content.setPreferredSize(null);
        jScrollPane1.setViewportView(txt_content);

        jLabel1.setText("File Name: ");

        txt_filename.setText("jTextField1");

        btn_cancel.setBackground(java.awt.Color.white);
        btn_cancel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelMouseEntered(evt);
            }
        });

        btn_delete.setBackground(java.awt.Color.white);
        btn_delete.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_delete.setText("Reset");
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deleteMouseEntered(evt);
            }
        });

        btn_read.setBackground(java.awt.Color.white);
        btn_read.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_read.setText("Read");
        btn_read.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_readMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_readMouseEntered(evt);
            }
        });

        btn_correct.setBackground(java.awt.Color.white);
        btn_correct.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_correct.setText("Auto Correct");
        btn_correct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_correctMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_correctMouseEntered(evt);
            }
        });

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brailleantv2/save.png"))); // NOI18N
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveMouseEntered(evt);
            }
        });
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_filename))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_read, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_correct, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(btn_read, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_correct, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_readMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_readMouseEntered
        // TODO add your handling code here:
        tts.speak("rid");
    }//GEN-LAST:event_btn_readMouseEntered

    private void btn_correctMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_correctMouseEntered
        // TODO add your handling code here:
        tts.speak("Auto correct");
    }//GEN-LAST:event_btn_correctMouseEntered

    private void btn_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseEntered
        // TODO add your handling code here:
        tts.speak("Cancel");
    }//GEN-LAST:event_btn_cancelMouseEntered

    private void btn_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseEntered
        // TODO add your handling code here:
        tts.speak("delete file");
    }//GEN-LAST:event_btn_deleteMouseEntered

    private void btn_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseEntered
        // TODO add your handling code here:
        tts.speak("save changes");
    }//GEN-LAST:event_btn_saveMouseEntered

    private void btn_readMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_readMouseClicked
        // TODO add your handling code here:
        tts.speak(txt_content.getText());
    }//GEN-LAST:event_btn_readMouseClicked

    private void btn_correctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_correctMouseClicked
        // TODO add your handling code here:
        String[] words=txt_content.getText().split(" ");
        for(int ctr=0; ctr<words.length; ctr++){
            words[ctr]=spellchecker.correct(words[ctr]);
        }
        String newContent="";
        for(String word : words){
            newContent=newContent.concat(word+" ");
        }
        txt_content.setText(newContent);
    }//GEN-LAST:event_btn_correctMouseClicked

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        // TODO add your handling code here:
        if(fromCamera){
            new CameraForm(this.tts).setVisible(true);
            dispose();
        }
        else{
            new ReadForm(this.tts,this.fileName).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        // TODO add your handling code here:
        try{
            File file=new File(Global.FILES_DIR+"/"+txt_filename.getText());
            file.createNewFile();
            FileWriter wr=new FileWriter(file);
            wr.write(txt_content.getText());
            wr.close();
            new ReadForm(this.tts,txt_filename.getText()).setVisible(true);
            dispose();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
        // TODO add your handling code here:
        txt_content.setText(this.originalString);
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_correct;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_read;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_content;
    private javax.swing.JTextField txt_filename;
    // End of variables declaration//GEN-END:variables
}
