/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brailleantv2;

import java.awt.Color;

/**
 *
 * @author Zildjian
 */
public class FilesForm extends javax.swing.JFrame {

    /**
     * Creates new form FilesForm
     */
    private TTS tts;
    private int totalFiles;
    private int currentFileIndex=0;
    public FilesForm() {
        this.tts=new TTS();
        initComponents();
    }
    public void init(){
        
        this.getContentPane().setBackground(Color.red);
        try{
            java.io.File files=new java.io.File(Global.FILES_DIR);
            list_files.setListData(files.list());
            totalFiles=files.list().length;
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    public FilesForm(TTS tts) {
        this.tts=tts;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_files = new javax.swing.JList<>();
        btn_mainMenu = new javax.swing.JButton();
        btn_prev = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(480, 320));
        setMinimumSize(new java.awt.Dimension(480, 320));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(480, 320));

        list_files.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_filesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_files);

        btn_mainMenu.setText("Main Menu");
        btn_mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mainMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mainMenuMouseEntered(evt);
            }
        });

        btn_prev.setText("<<");
        btn_prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_prevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_prevMouseEntered(evt);
            }
        });

        btn_next.setText(">>");
        btn_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nextMouseEntered(evt);
            }
        });

        btn_select.setText("Select");
        btn_select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_selectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_selectMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_select, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_next, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(btn_prev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_select, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mainMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainMenuMouseEntered
        // TODO add your handling code here:
        tts.speak("Main Menu");
    }//GEN-LAST:event_btn_mainMenuMouseEntered

    private void btn_prevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prevMouseEntered
        // TODO add your handling code here:
        tts.speak("Previous File");
    }//GEN-LAST:event_btn_prevMouseEntered

    private void btn_nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMouseEntered
        // TODO add your handling code here:
        tts.speak("Next File");
    }//GEN-LAST:event_btn_nextMouseEntered

    private void btn_selectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selectMouseEntered
        // TODO add your handling code here:
        tts.speak("Select "+list_files.getSelectedValue());
    }//GEN-LAST:event_btn_selectMouseEntered

    private void btn_prevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prevMouseClicked
        // TODO add your handling code here:
        currentFileIndex=currentFileIndex==0? totalFiles-1: currentFileIndex-1; 
        list_files.setSelectedIndex(currentFileIndex);
        tts.speak(list_files.getSelectedValue());
    }//GEN-LAST:event_btn_prevMouseClicked

    private void btn_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMouseClicked
        // TODO add your handling code here:
        currentFileIndex=currentFileIndex==totalFiles-1? 0: currentFileIndex+1; 
        list_files.setSelectedIndex(currentFileIndex);
        tts.speak(list_files.getSelectedValue());
    }//GEN-LAST:event_btn_nextMouseClicked

    private void btn_selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selectMouseClicked
        // TODO add your handling code here:
        tts.speak(list_files.getSelectedValue()+" selected");
        new ReadForm(this.tts,list_files.getSelectedValue()).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_selectMouseClicked

    private void list_filesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_filesValueChanged
        // TODO add your handling code here:
        tts.speak(list_files.getSelectedValue());
    }//GEN-LAST:event_list_filesValueChanged

    private void btn_mainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainMenuMouseClicked
        // TODO add your handling code here:
        new MainForm(this.tts).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_mainMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mainMenu;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_prev;
    private javax.swing.JButton btn_select;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_files;
    // End of variables declaration//GEN-END:variables
}
