/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brailleantv2;

import java.awt.Color;

/**
 *
 * @author pi
 */
public class MainForm extends javax.swing.JFrame {

    TTS tts;
    private int index = 0;

    /**
     * Creates new form MainForm
     */
    private void init(){
        this.getContentPane().setBackground(Color.red);
    }
    public MainForm() {
        initComponents();
        tts=new TTS();
        tts.start();
        init();
    }
    public MainForm(TTS tts){
        initComponents();
        this.tts=tts;
        init();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Shutdown = new javax.swing.JButton();
        btn_Camera = new javax.swing.JButton();
        btn_Files = new javax.swing.JButton();
        btn_Options = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(480, 320));
        setMinimumSize(new java.awt.Dimension(480, 320));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(480, 320));

        btn_Shutdown.setBackground(java.awt.Color.white);
        btn_Shutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brailleantv2/shutdown.png"))); // NOI18N
        btn_Shutdown.setMaximumSize(new java.awt.Dimension(150, 150));
        btn_Shutdown.setMinimumSize(new java.awt.Dimension(150, 150));
        btn_Shutdown.setPreferredSize(new java.awt.Dimension(150, 150));
        btn_Shutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ShutdownMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ShutdownMouseEntered(evt);
            }
        });
        btn_Shutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShutdownActionPerformed(evt);
            }
        });

        btn_Camera.setBackground(java.awt.Color.white);
        btn_Camera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brailleantv2/camera.png"))); // NOI18N
        btn_Camera.setMaximumSize(new java.awt.Dimension(150, 150));
        btn_Camera.setMinimumSize(new java.awt.Dimension(150, 150));
        btn_Camera.setPreferredSize(new java.awt.Dimension(150, 150));
        btn_Camera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CameraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CameraMouseEntered(evt);
            }
        });

        btn_Files.setBackground(java.awt.Color.white);
        btn_Files.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brailleantv2/file.png"))); // NOI18N
        btn_Files.setMaximumSize(new java.awt.Dimension(150, 150));
        btn_Files.setMinimumSize(new java.awt.Dimension(150, 150));
        btn_Files.setPreferredSize(new java.awt.Dimension(150, 150));
        btn_Files.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FilesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_FilesMouseEntered(evt);
            }
        });

        btn_Options.setBackground(java.awt.Color.white);
        btn_Options.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brailleantv2/options.png"))); // NOI18N
        btn_Options.setMaximumSize(new java.awt.Dimension(150, 150));
        btn_Options.setMinimumSize(new java.awt.Dimension(150, 150));
        btn_Options.setPreferredSize(new java.awt.Dimension(150, 150));
        btn_Options.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_OptionsMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Files, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btn_Shutdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Options, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Camera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Camera, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btn_Shutdown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Files, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void action() {
        switch (this.index) {
            case 1:
                try {
                    tts.speak("Shutting down.");
                    //Runtime.getRuntime().exec("shutdown -t 60");
                    this.setVisible(false);
                    new ShutdownFrame(tts,this).setVisible(true);
                    //dispose();
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                break;
            case 2:
                tts.speak("RBD Options Selected");
                break;
            case 3:                
                tts.speak("Camera Selected");
                new CameraForm(this.tts).setVisible(true);
                dispose();
                break;
            case 4:
                
                tts.speak("Scanner Selected");
                break;
            case 5:
                
                tts.speak("Files Selected");
                break;
            case 6:
                dispose();
                break;
            default:
                System.out.println("Unknown case "+this.index);
        }
    }
    private void btn_ShutdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ShutdownMouseEntered
        // TODO add your handling code here:
        tts.speak("Shutdown Device");
        this.index=1;
    }//GEN-LAST:event_btn_ShutdownMouseEntered

    private void btn_CameraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CameraMouseEntered
        // TODO add your handling code here:
        tts.speak("Camera");
        this.index=3;
    }//GEN-LAST:event_btn_CameraMouseEntered

    private void btn_FilesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FilesMouseEntered
        // TODO add your handling code here:
        tts.speak("Files");
        this.index=5;
    }//GEN-LAST:event_btn_FilesMouseEntered

    private void btn_OptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OptionsMouseEntered
        // TODO add your handling code here:
        tts.speak("Advanced Options");
        this.index=6;
    }//GEN-LAST:event_btn_OptionsMouseEntered

    private void btn_ShutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ShutdownMouseClicked
        // TODO add your handling code here:
        action();
    }//GEN-LAST:event_btn_ShutdownMouseClicked

    private void btn_CameraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CameraMouseClicked
        // TODO add your handling code here:
        action();
    }//GEN-LAST:event_btn_CameraMouseClicked

    private void btn_FilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FilesMouseClicked
        // TODO add your handling code here:
        action();
        new FilesForm(this.tts).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_FilesMouseClicked

    private void btn_OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OptionsMouseClicked
        // TODO add your handling code here:
        action();
        System.exit(0);
    }//GEN-LAST:event_btn_OptionsMouseClicked

    private void btn_ShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShutdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ShutdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Camera;
    private javax.swing.JButton btn_Files;
    private javax.swing.JButton btn_Options;
    private javax.swing.JButton btn_Shutdown;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
